### ISSUE TITLE
local build error

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#23] opened 2019-03-01 11:46 UTC
```
ERROR: error loading package 'lingvo': Encountered error while reading extension file 'subpar.bzl': no such package '@subpar//': Traceback (most recent call last):
        File "/home/luban/.cache/bazel/_bazel_luban/b5ef85f1c360696308ba7ab9000cfd03/external/bazel_tools/tools/build_defs/repo/git.bzl", line 166
                _clone_or_update(ctx)
        File "/home/luban/.cache/bazel/_bazel_luban/b5ef85f1c360696308ba7ab9000cfd03/external/bazel_tools/tools/build_defs/repo/git.bzl", line 72, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning subpar:
```

**Comment by drpngx** [comment] 2019-03-01 23:11
What bazel version are you using? Can you try `0.17.2`?

**Comment by jonathanasdf** [comment] 2019-03-02 00:26
Can you please run this script

https://github.com/tensorflow/lingvo/blob/master/tf_env_collect.sh

**Comment by zh794390558** [comment] 2019-03-03 01:24
solved by updating git version to 2.18.0, thanks.

**Comment by zh794390558** [comment] 2019-03-03 01:32
```

== cat /etc/issue ===============================================
Linux luban-351 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
Yes

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== bazel =====================================================
Build label: 0.17.2
Build time: Fri Sep 21 10:31:42 2018 (1537525902)
Build timestamp: 1537525902
Build timestamp as int: 1537525902

== uname -a =====================================================
Linux luban-351 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy               1.15.4    
protobuf            3.6.1     
tensorflow          1.12.0    

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.12.0
tf.GIT_VERSION = b'unknown'
tf.COMPILER_VERSION = b'unknown'
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /nfs/project/tools/anaconda3/pkgs/cudnn-7.2.1-cuda9.2_0/lib:/nfs/project/tools/anaconda3/pkgs/cudatoolkit-9.2-0/lib:/usr/local/nccl_2.3.7-1+cuda10.0_x86_64/lib/:/usr/local/cuda-9.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Sun Mar  3 09:29:55 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.72       Driver Version: 410.72       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   40C    P0    67W / 250W |  16827MiB / 22919MiB |     29%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:03:00.0 Off |                  N/A |
| N/A   41C    P0    69W / 250W |  16827MiB / 22919MiB |     30%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P40           Off  | 00000000:83:00.0 Off |                  N/A |
| N/A   23C    P8    10W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P40           Off  | 00000000:84:00.0 Off |                  N/A |
| N/A   23C    P8    10W / 250W |     10MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.61
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart_static.a
```

**Comment by drpngx** [comment] 2019-03-03 01:33
Good to know. We'll update the README.

**Comment by zh794390558** [comment] 2019-03-03 01:42
```
ERROR: /nfs/project/zhanghui/lingvo/lingvo/core/BUILD:339:1: no such package '@protobuf_protoc//': java.io.IOException: Error downloading [https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip] to /home/luban/.cache/bazel/_bazel_luban/b5ef85f1c360696308ba7ab9000cfd03/external/protobuf_protoc/protoc-3.6.1-linux-x86_64.zip: GET returned 403 Forbidden and referenced by '//lingvo/core:inference_graph_py_pb2_genpy'
ERROR: Analysis of target '//lingvo:trainer_test' failed; build aborted: no such package '@protobuf_protoc//': java.io.IOException: Error downloading [https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip] to /home/luban/.cache/bazel/_bazel_luban/b5ef85f1c360696308ba7ab9000cfd03/external/protobuf_protoc/protoc-3.6.1-linux-x86_64.zip: GET returned 403 Forbidden
INFO: Elapsed time: 422.566s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded)
FAILED: Build did NOT complete successfully (2 packages loaded)
```

**Comment by drpngx** [comment] 2019-03-03 01:44
I just tried and I'm able to download that file. Is it possible that you're under a firewall that blocks the download?

**Comment by zh794390558** [comment] 2019-03-03 01:46
Maybe, how can I install this offline, if i have this package.

**Comment by drpngx** [comment] 2019-03-03 01:48
Currently there's no option to use a local package. If you have a local
mirror, then the location is specified in repo.bzl

**Comment by zh794390558** [comment] 2019-03-03 02:22
http_archive will download zip without check if the target zip existing. How can I change the code to check local exists or just extracting the zip directly?
```
def _http_archive_impl(ctx):
    """Implementation of the http_archive rule."""
    if not ctx.attr.url and not ctx.attr.urls:
        fail("At least one of url and urls must be provided")
    if ctx.attr.build_file and ctx.attr.build_file_content:
        fail("Only one of build_file and build_file_content can be provided.")

    all_urls = []
    if ctx.attr.urls:
        all_urls = ctx.attr.urls
    if ctx.attr.url:
        all_urls = [ctx.attr.url] + all_urls

    ctx.download_and_extract(
        all_urls,
        "",
        ctx.attr.sha256,
        ctx.attr.type,
        ctx.attr.strip_prefix,
    )
    patch(ctx)
    workspace_and_buildfile(ctx)
```

**Comment by drpngx** [comment] 2019-03-03 03:05
I am loath to introduce a way to pick up local binaries, since it circumvents the idea of hermetic builds. That would make debugging harder. You can download the file by any means necessary and then specify `file://` as the url.

**Comment by zh794390558** [comment] 2019-03-03 03:50
thanks, work for me.

https://github.com/tensorflow/lingvo/blob/master/lingvo/repo.bzl#L5
https://github.com/tensorflow/lingvo/blob/master/lingvo/repo.bzl#L19

These functions not work when I using virtual env for tensorflow.

**Comment by zh794390558** [comment] 2019-03-03 03:51
```
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //lingvo:trainer_test (31 packages loaded).
INFO: Found 1 test target...
ERROR: /nfs/project/zhanghui/lingvo/lingvo/tools/BUILD:98:1: Linking of rule '//lingvo/tools:generate_proto_def' failed (Exit 1)
bazel-out/host/bin/lingvo/tools/_objs/generate_proto_def/generate_proto_def.o:generate_proto_def.cc:function (anonymous namespace)::WriteDotProto(google::protobuf::FileDescriptor const*, char const*): error: undefined reference to 'google::protobuf::FileDescriptor::DebugString() const'
collect2: error: ld returned 1 exit status
Target //lingvo:trainer_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.259s, Critical Path: 2.09s
INFO: 2 processes: 2 processwrapper-sandbox.
FAILED: Build did NOT complete successfully

FAILED: Build did NOT complete successfully
```

**Comment by drpngx** [comment] 2019-03-09 18:07
This is a duplicate of #32 -- let's continue the discussion there.

**Closed by drpngx** 2019-03-09 18:07 UTC
